---
app_username: dienstplan
app_usergroup: web
app_directory: /opt/dienstplan

app_files_chmod: "0644"
app_resources_chmod: "0755"
env_files_chmod: "0600"

systemd_service_env: /etc/opt/dienstplan.env

systemd_migrate_name: dienstplan-migrate.service
systemd_migrate_file: /etc/systemd/system/{{ systemd_migrate_name }}

systemd_rollback_name: dienstplan-rollback.service
systemd_rollback_file: /etc/systemd/system/{{ systemd_rollback_name }}

systemd_service_name: dienstplan-server.service
systemd_service_file: /etc/systemd/system/{{ systemd_service_name }}


nginx_config_file: /etc/nginx/sites-available/default
nginx_config_symlink: /etc/nginx/sites-enabled/default
nginx_config_chmod: "0644"

local_path: "../dienstplan"
app_local_directory: "{{ local_path }}/target/uberjar/"
resources_local_directory: "{{ local_path }}/resources/"

app_resources: resources
# FIXME change version!
# or simply override with command-line option: -e app_version=0.1.3
app_version: 0.1.3
app_file: "dienstplan-{{ app_version }}-standalone.jar"
