---
service_usergroup: web
service_username: dienstplan

service_directory: /opt/dienstplan
service_files_chmod: '0644'
service_resources_chmod: '0755'
env_files_chmod: '0600'

systemd_service_name: dienstplan.service
systemd_service_file: /etc/systemd/system/{{ systemd_service_name }}
systemd_service_env: /etc/opt/dienstplan.env
